//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASF.UI.WbSite.ServicesReferenced {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicesReferenced.WebService1Soap")]
    public interface WebService1Soap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento venc del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidarTarjeta", ReplyAction="*")]
        ASF.UI.WbSite.ServicesReferenced.ValidarTarjetaResponse ValidarTarjeta(ASF.UI.WbSite.ServicesReferenced.ValidarTarjetaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ValidarTarjeta", ReplyAction="*")]
        System.Threading.Tasks.Task<ASF.UI.WbSite.ServicesReferenced.ValidarTarjetaResponse> ValidarTarjetaAsync(ASF.UI.WbSite.ServicesReferenced.ValidarTarjetaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento AgregarCreditoResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarCredito", ReplyAction="*")]
        ASF.UI.WbSite.ServicesReferenced.AgregarCreditoResponse AgregarCredito(ASF.UI.WbSite.ServicesReferenced.AgregarCreditoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AgregarCredito", ReplyAction="*")]
        System.Threading.Tasks.Task<ASF.UI.WbSite.ServicesReferenced.AgregarCreditoResponse> AgregarCreditoAsync(ASF.UI.WbSite.ServicesReferenced.AgregarCreditoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarTarjetaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarTarjeta", Namespace="http://tempuri.org/", Order=0)]
        public ASF.UI.WbSite.ServicesReferenced.ValidarTarjetaRequestBody Body;
        
        public ValidarTarjetaRequest() {
        }
        
        public ValidarTarjetaRequest(ASF.UI.WbSite.ServicesReferenced.ValidarTarjetaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarTarjetaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public long Nro;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public double Saldo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string venc;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int seg;
        
        public ValidarTarjetaRequestBody() {
        }
        
        public ValidarTarjetaRequestBody(long Nro, double Saldo, string venc, int seg) {
            this.Nro = Nro;
            this.Saldo = Saldo;
            this.venc = venc;
            this.seg = seg;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ValidarTarjetaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ValidarTarjetaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ASF.UI.WbSite.ServicesReferenced.ValidarTarjetaResponseBody Body;
        
        public ValidarTarjetaResponse() {
        }
        
        public ValidarTarjetaResponse(ASF.UI.WbSite.ServicesReferenced.ValidarTarjetaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ValidarTarjetaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ValidarTarjetaResult;
        
        public ValidarTarjetaResponseBody() {
        }
        
        public ValidarTarjetaResponseBody(string ValidarTarjetaResult) {
            this.ValidarTarjetaResult = ValidarTarjetaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarCreditoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarCredito", Namespace="http://tempuri.org/", Order=0)]
        public ASF.UI.WbSite.ServicesReferenced.AgregarCreditoRequestBody Body;
        
        public AgregarCreditoRequest() {
        }
        
        public AgregarCreditoRequest(ASF.UI.WbSite.ServicesReferenced.AgregarCreditoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarCreditoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int Monto;
        
        public AgregarCreditoRequestBody() {
        }
        
        public AgregarCreditoRequestBody(int Monto) {
            this.Monto = Monto;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AgregarCreditoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AgregarCreditoResponse", Namespace="http://tempuri.org/", Order=0)]
        public ASF.UI.WbSite.ServicesReferenced.AgregarCreditoResponseBody Body;
        
        public AgregarCreditoResponse() {
        }
        
        public AgregarCreditoResponse(ASF.UI.WbSite.ServicesReferenced.AgregarCreditoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AgregarCreditoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AgregarCreditoResult;
        
        public AgregarCreditoResponseBody() {
        }
        
        public AgregarCreditoResponseBody(string AgregarCreditoResult) {
            this.AgregarCreditoResult = AgregarCreditoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebService1SoapChannel : ASF.UI.WbSite.ServicesReferenced.WebService1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebService1SoapClient : System.ServiceModel.ClientBase<ASF.UI.WbSite.ServicesReferenced.WebService1Soap>, ASF.UI.WbSite.ServicesReferenced.WebService1Soap {
        
        public WebService1SoapClient() {
        }
        
        public WebService1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebService1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ASF.UI.WbSite.ServicesReferenced.ValidarTarjetaResponse ASF.UI.WbSite.ServicesReferenced.WebService1Soap.ValidarTarjeta(ASF.UI.WbSite.ServicesReferenced.ValidarTarjetaRequest request) {
            return base.Channel.ValidarTarjeta(request);
        }
        
        public string ValidarTarjeta(long Nro, double Saldo, string venc, int seg) {
            ASF.UI.WbSite.ServicesReferenced.ValidarTarjetaRequest inValue = new ASF.UI.WbSite.ServicesReferenced.ValidarTarjetaRequest();
            inValue.Body = new ASF.UI.WbSite.ServicesReferenced.ValidarTarjetaRequestBody();
            inValue.Body.Nro = Nro;
            inValue.Body.Saldo = Saldo;
            inValue.Body.venc = venc;
            inValue.Body.seg = seg;
            ASF.UI.WbSite.ServicesReferenced.ValidarTarjetaResponse retVal = ((ASF.UI.WbSite.ServicesReferenced.WebService1Soap)(this)).ValidarTarjeta(inValue);
            return retVal.Body.ValidarTarjetaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ASF.UI.WbSite.ServicesReferenced.ValidarTarjetaResponse> ASF.UI.WbSite.ServicesReferenced.WebService1Soap.ValidarTarjetaAsync(ASF.UI.WbSite.ServicesReferenced.ValidarTarjetaRequest request) {
            return base.Channel.ValidarTarjetaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ASF.UI.WbSite.ServicesReferenced.ValidarTarjetaResponse> ValidarTarjetaAsync(long Nro, double Saldo, string venc, int seg) {
            ASF.UI.WbSite.ServicesReferenced.ValidarTarjetaRequest inValue = new ASF.UI.WbSite.ServicesReferenced.ValidarTarjetaRequest();
            inValue.Body = new ASF.UI.WbSite.ServicesReferenced.ValidarTarjetaRequestBody();
            inValue.Body.Nro = Nro;
            inValue.Body.Saldo = Saldo;
            inValue.Body.venc = venc;
            inValue.Body.seg = seg;
            return ((ASF.UI.WbSite.ServicesReferenced.WebService1Soap)(this)).ValidarTarjetaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ASF.UI.WbSite.ServicesReferenced.AgregarCreditoResponse ASF.UI.WbSite.ServicesReferenced.WebService1Soap.AgregarCredito(ASF.UI.WbSite.ServicesReferenced.AgregarCreditoRequest request) {
            return base.Channel.AgregarCredito(request);
        }
        
        public string AgregarCredito(int Monto) {
            ASF.UI.WbSite.ServicesReferenced.AgregarCreditoRequest inValue = new ASF.UI.WbSite.ServicesReferenced.AgregarCreditoRequest();
            inValue.Body = new ASF.UI.WbSite.ServicesReferenced.AgregarCreditoRequestBody();
            inValue.Body.Monto = Monto;
            ASF.UI.WbSite.ServicesReferenced.AgregarCreditoResponse retVal = ((ASF.UI.WbSite.ServicesReferenced.WebService1Soap)(this)).AgregarCredito(inValue);
            return retVal.Body.AgregarCreditoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ASF.UI.WbSite.ServicesReferenced.AgregarCreditoResponse> ASF.UI.WbSite.ServicesReferenced.WebService1Soap.AgregarCreditoAsync(ASF.UI.WbSite.ServicesReferenced.AgregarCreditoRequest request) {
            return base.Channel.AgregarCreditoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ASF.UI.WbSite.ServicesReferenced.AgregarCreditoResponse> AgregarCreditoAsync(int Monto) {
            ASF.UI.WbSite.ServicesReferenced.AgregarCreditoRequest inValue = new ASF.UI.WbSite.ServicesReferenced.AgregarCreditoRequest();
            inValue.Body = new ASF.UI.WbSite.ServicesReferenced.AgregarCreditoRequestBody();
            inValue.Body.Monto = Monto;
            return ((ASF.UI.WbSite.ServicesReferenced.WebService1Soap)(this)).AgregarCreditoAsync(inValue);
        }
    }
}
