//====================================================================================================
// Base code generated with LeatherGoods - ASF.Services.Contracts
// Architecture Solutions Foundation
//
// Generated by academic at LeatherGoods V 1.0 
//====================================================================================================

using System;
using System.ComponentModel;
using System.Collections.Generic;
using System.Runtime.Serialization;
using ASF.Entities;


namespace ASF.Services.Contracts
{
    
    [DataContract]
    public class FindCategoryResponse
    {
        [DataMember]
        public Category Result { get; set; }
    }

    [DataContract]
    public class FindCountryResponse
    {
        [DataMember]
        public Country Result { get; set; }
    }

    [DataContract]
    public class FindDealerResponse
    {
        [DataMember]
        public Dealer Result { get; set; }
    }

    [DataContract]
    public class FindClientResponse
    {
        [DataMember]
        public Client Result { get; set; }
    }

    [DataContract]
    public class FindProductResponse
    {
        [DataMember]
        public Product Result { get; set; }
    }

    [DataContract]
    public class FindRatingResponse
    {
        [DataMember]
        public Rating Result { get; set; }
    }

    [DataContract]
    public class FindOrderDetailResponse
    {
        [DataMember]
        public OrderDetail Result { get; set; }
    }

    [DataContract]
    public class FindOrderResponse
    {
        [DataMember]
        public Order Result { get; set; }
    }

    [DataContract]
    public class FindCartResponse
    {
        [DataMember]
        public Cart Result { get; set; }
    }

    [DataContract]
    public class FindCartItemResponse
    {
        [DataMember]
        public CartItem Result { get; set; }
    }

    [DataContract]
    public class FindOrderNumberResponse
    {
        [DataMember]
        public OrderNumber Result { get; set; }
    }

    [DataContract]
    public class FindErrorResponse
    {
        [DataMember]
        public Error Result { get; set; }
    }

    [DataContract]
    public class FindSettingResponse
    {
        [DataMember]
        public Setting Result { get; set; }
    }

    [DataContract]
    public class FindLanguageResponse
    {
        [DataMember]
        public Language Result { get; set; }
    }

    [DataContract]
    public class FindLocaleResourceKeyResponse
    {
        [DataMember]
        public LocaleResourceKey Result { get; set; }
    }

    [DataContract]
    public class FindLocaleStringResourceResponse
    {
        [DataMember]
        public LocaleStringResource Result { get; set; }
    }
}

